### ISSUE TITLE
OKR Sep

### ISSUE THREAD

**Issue by anhhuy0501** [massbitprotocol/massbitprotocol#189]
# Detail task
From OKR Aug.
- Merge code so + wasm

- New ferature
  - New demo from other (uniswap, pancakeswap)
  - Cache data chain-reader -> data into DB/File 
  - Docker for dev (2 Sep)
  - Argument for Chain-reader (1 Sep)
  - Choose Hasura or no relationship (1 Sep)
  - Relation ship in DB (1 Sep)
  - User reg/login/DB
  - Support wasm for Solana/Substrate (? is need for selling point)
  

- Code  quality
  - Refactor 
    - Clean unused code + lib + warning (1 Sep)
    - Chain-reader: use trait for cleaner code (1 Sep)
    - Chain-reader: reduce encode-decode time (1 Sep)
    - Store: into separate module (1 Sep)
    - Log: to file -> ELK later? 
    - Clean directory tree -> move unused folder (1 Sep)
    - Add lint code (2 Sep)
    - Use prelude to avoid version conflict (1 Sep)
    - Separate Code-compiler to new repo (1 Sep)

  - Stable:
    - User custom code management -> avoid abuse code in playground
      - DB/log storage volume/connection limit, 
      - CPU limit time/percent of CPU
      - Limit Indexer number

  - Scale  
    - Fix bug Docker (1 Sep)
    - Use Bigquery for DB ->?
  - Optimize:
    - Run as debug or release
    - Reduce Compile time wasm -> <1min (1 Sep)
    - Reduce Compile time so -> <1min (2 Sep)
    - Cache query Hasura (depend on query content) 
    - Add metric data Prometheus (1 Sep)
  
  - Test:
    - Unit test 
    - Integration test (1 Sep)
    - Mock data for all (1 Sep)
    - Code coverage
    - Long run test (1 Sep)

**Comment by daywednes** [comment]
- support coin98 insight feature
- frontend work for massbit

**Comment by daywednes** [comment]
https://drive.google.com/file/d/1qDOV6X5crtaszIr4GqeNRfmL8dqeTG0b/view

Coin98 report example

**Comment by anhhuy0501** [comment]
# OKR September (summary)
## New features
- Support coin98 insight feature
- Frontend work for massbit (support API for frontend)
- Add Metric data service for Massbit Indexer

## Code quality
- Stable: Run in > 1 week
- Integration test for (Chain-reader, Index-manager, Code-compiler, wasm/so plugin, code-gen)
- Optimize wasm compile time < 1min
