### ISSUE TITLE
Some OS tuning tips 

### ISSUE THREAD

**Issue by baysao** [massbitprotocol/massbitprotocol#233]
## Increase max open files 
* Sysctl: increase max open file to 6816768
   Edit file /etc/sysctl.conf with line 
 ` fs.file-max=6816768` 
Apply config with command 
`sysctl -p`

* Ulimit: Increase number file open to 99999 and max process to 20000 to massbit (fill * in case all users)
  Edit file  /etc/security/limits.conf with line
```
massbit       soft    nofile  99999
massbit      hard    nofile  99999
massbit      soft    noproc  20000
massbit       hard    noproc  20000

```
Check config with command:
`su - massbit -c 'ulimit -a'`

## Other kernel tunning in sysctl.conf
```
vm.max_map_count=1048576
vm.min_free_kbytes=65535
vm.overcommit_memory=1
vm.swappiness=0
vm.vfs_cache_pressure=50
net.ipv4.ip_local_port_range = 18000    65535
net.netfilter.nf_conntrack_tcp_timeout_established=86400
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc = fq
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_keepalive_time = 30
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_fastopen=3

```

**Comment by thala321** [comment]
Thanks @baysao 
I'll add this in the PSOP's document.

**Comment by thala321** [comment]
The OS tuning tips are added in this PR https://github.com/massbitprotocol/massbitprotocol/pull/244/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
