### ISSUE TITLE
Exercise for Fullstack Candidates

### ISSUE THREAD

**Issue by anhhuy0501** [massbitprotocol/massbitprotocol#255]
Exercise for fullstack candidates

**Comment by thala321** [comment]
Frontend requirements
- Able to write FE charts
- Vuejs, Reactjs
- ...

Backend requirements:
- Mostly work with Business Logic (create a new User service)
- Any backend language is ok 
- Will be trained to work with Rust
- Blockchain knowledge is a plus

Detail tests:
- to be added.

**Comment by thala321** [comment]
I want to standardize our interview tests by grouping them all into 1 place. Maybe Gitbook / Google Docs  / ...
Can you give me your previous Rust tests @daywednes
