### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by anhhuy0501** [massbitprotocol/massbitprotocol#280]
# 06 Oct.
- @thala321 : Solana node is up, waiting for sync (in about 1-2 weeks) -> 07 Oct. Check sync status
- @vuviettai : 
  - Get 5 more parameters: block_counter, average block time, total/success transactions, total rewards, total fee
  -> 07 Oct. run long test for checking DB performance.
- @datzero9 : merge GRPC chain-reader into index-manager -> 07 Oct. write Solana data into db
- @anhhuy0501: refactoring chain-reader for filtering Solana block -> 07 Oct. finish filtering and decoding.

- @baysao : Finished Platform base, https://github.com/massbitprotocol/massbitroute/commit/9a7aa3f40a83ce08fcfeba76afd7c5ebf707ec2e

**Comment by thala321** [comment]
07 Oct.
@thala321 : 
- Solana node is up. RPC call is still slow.
- Long tests: Harmony, ethereum analytics, solana analytics
 
@vuviettai :
- parse Solana system instruction (in-progress). 10 types of instructions
 
@datzero9 :
- parse Saber data smart contract

@anhhuy0501: 
- refactor Solana chain-reader
- add filters for Solana

@baysao : 
- api token (done)
- entrypoint (done)

**Comment by thala321** [comment]
# 08 Oct.
@thala321 : 
- Run chain-reader in the same server with Solana node to increase data-consuming speed
- Debug why Solana-analytic is slow (in progress)
 
@vuviettai : 
System instruction: parse data into separated tables for all system instruction types: 
- createAccount, 
- createAccountWithSeed, 
- Assign
- assignWithSeed
- Transfer
- transferWithSeed
- Allocate
- allocateWithSeed
- advanceNonce
- withdrawFromNonce
- initializeNonce
- authorizeNonce

@datzero9 :
- Read Saber instruction data
- Write .SO runtime for Solana

@anhhuy0501: 
- Chain-reader filters Solana smart contract
- Saber Stable Swap Program

@baysao : 
- integrate Infura and Getblock provider, and add load-balance

**Comment by thala321** [comment]
No longer use meeting note, we'll update the progress in Github project
