### ISSUE TITLE
Indexing Serum & Build Framework

### ISSUE THREAD

**Issue by anhhuy0501** [massbitprotocol/massbitprotocol#323]
**Research**
- [x] Understand Serum code (2days) @vuviettai 

**Framework**:
- Check: 
  - Add handler in plugin adapter to handle user logic. 
  - Dynamic Datasource support (unknown)

- Features: 
- [x] handle GraphQL to generate model **(5-11 -> next week)**  @vuviettai 
- [x] `new` chain-reader, filter by block @anhhuy0501   
- [x] CLI to parse instruction structure **(5-11 -> 12-11)** 
  - [x] Upload our Indexer CLI to crates.io @anhhuy0501
  - [x] Run Codegen (add params to choose existing smart contract (Saber, Serum)) (9-11)
    - generate model @anhhuy0501  (90%)
    - generate handler @vuviettai  (50%)
    - **generate instruction** @vuviettai  (90%)
    - generate graph schema @anhhuy0501  (90%)
  - [x] Research How to define Json structure from public rust lib / polkadot (0.5 day -> 1 day -> 2 days) -> write custom
  - [x] test CLI for serum @anhhuy0501 
  - [x] `new` bug for serum (instruction syntax error)

**Apply Framework for Serum:** 
- [x] (Serum) user defines Manifest  @vuviettai
- [x] (Serum) user defines instruction structure  **(5-11)** @vuviettai @anhhuy0501  (in-progress)
- [x] (Saber) user defines instruction structure  **(5-11)** @vuviettai  (in-progress)
- [x] (Serum) Store raw data (account fields) **(5-11 -> 12-11)** @anhhuy0501   (in-progress)

- [x] design / draw architecture for the framework @vuviettai  (29-10)
![SolanaSmartContractIndexer drawio (1)](https://user-images.githubusercontent.com/71484461/139232980-fa73c853-65b7-4e7f-b964-a1631bec8db9.png)

**Comment by thala321** [comment]
Demo for Friday (5-11)

- Run CLI 
- Auto generate indexing logic
- Deploy Indexing Logic
- See the data in the DB
