### ISSUE TITLE
Tai works

### ISSUE THREAD

**Issue by daywednes** [massbitprotocol/massbitprotocol#49]
1. Understand Anh Huy's logic work
2. Understand hughie's logic work 
3. Understand manhdat's logic work 
4. Create 3 issues to improve code from all the codebase.

**Comment by vuviettai** [comment]
1. Replace constants using in code by config parameters. Some constants like: buffer size, ip address, urls
2. Reduce repetition in similar code: Chain reader/plugin for substrate and solana
3. Separate logic layer and database access layer
4. Question??: will we support custom database or separated db for each user
