### ISSUE TITLE
Rewrite indexing logic of subquery examples in rust

### ISSUE THREAD

**Issue by daywednes** [massbitprotocol/massbitprotocol#5]
## Subquery examples

1. Look at and study https://github.com/subquery/subql-examples/
2. Define architecture of data model in rust
3. Study which modules or lib from substrate or polkadot rust we need to import for indexing
4. Design and implement `code-gen` before running indexing simulation
5. Design and implement 3 examples of subquery.

**Comment by datzero9** [comment]
- Research subql, substrate and define data model: 2 days
- Implement pipeline (fetch data, store db, ...): 4 days
- Code generator: 3 days
