### ISSUE TITLE
Meeting note (Daily update)

### ISSUE THREAD

**Issue by anhhuy0501** [massbitprotocol/massbitprotocol#65]
## 20 July
@anhhuy0501 task:
- Write user code + query for demo -> create template code
- Testing
Solana cannot insert data after 10 min -> Edit code to reduce congest

@thala321 @vuviettai 
Do test
- Create EC2 for test in long time:
  - 1 for substrate
  - 1 for solana
  - 1 for both
- Create test on self PC:
  - Run both chain in long time 
- Check why in docker cannot improve build time 

@NhutVu23 
- Support if there are front end bug
- Add new template to front end

**Comment by daywednes** [comment]
1. Batching writing to Postgres (@vuviettai)
2. @anhhuy0501 Serum examples
3. @thala321 setup github workflow

**Comment by anhhuy0501** [comment]
## 22 July
@anhhuy0501 task:
- Support compound type (with @vuviettai)
- Fully decode Solana
- Add example for Serum

@vuviettai
- Support compound type (with @anhhuy0501)
- Add function for storage
- User manager DB

@thala321 
- Complete CICD workflow

@NhutVu23
- Support import Github 

@datzero9 
- Gencode for compound type
- Research use WASM plugin (maybe reuse the graph code)

**Comment by anhhuy0501** [comment]
## 23 July
@anhhuy0501 task:
- Support compound type (with @vuviettai)
  - Schema for Serum (today)
  - Query for Serum (today)
 
@vuviettai
- Support compound type (with @anhhuy0501) 
- Add function for storage 
- User manager DB 

@thala321 
- Complete CICD workflow (today)

@NhutVu23
- Support import Github 

@datzero9 
- Gencode for compound type (finish by 26/7)
- Research use WASM plugin (maybe reuse the graph code)

Notes:
- We should use the free PC for long time testing. (@thala321 support)

**Comment by anhhuy0501** [comment]
## 26 July
@anhhuy0501 task:
- Support compound type
  - Query for Serum
  - Check and add @datzero9 code with @thala321 

 
@vuviettai
- Support compound type
  - Merge code to interact with index manager with @thala321 
- Generate code for table relation

@thala321 
- Fix CICD workflow
- Support @vuviettai for compound type.
  - Try to run an example from DDL gen CLI 
  - [Indexer] Call DDL gen cli from when received schema.graphql to run the migration 
  - [Indexer] Call API to track multiple tables in hasura 
  - Integration with frontend Dashboard from Vu

@NhutVu23
- Support import Github 
- Add UI for gencode

@datzero9 
- Research use WASM plugin (maybe reuse the graph code)

**Comment by anhhuy0501** [comment]
## 27 July
@anhhuy0501 task:
- Support compound type
  - Add example write compound type
  - Review + merge code

@vuviettai
- Support compound type
  - Write data in order for the relationship constrain
- Merge code with indexer

@thala321 
- Support @vuviettai for compound type.
  - Try to run an example from DDL gen CLI 
  - [Indexer] Call DDL gen cli from when received schema.graphql to run the migration 
  - [Indexer] Call API to track multiple tables in hasura 

@NhutVu23
- Add UI for gencode

@datzero9 
- Research use WASM plugin (maybe reuse the graph code)

**Comment by anhhuy0501** [comment]
## 28 July
@anhhuy0501 task:
- Support compound type
  - Fix generate code rust
  - Add json file for Frontend get examples and add a folder of examples
  - Review + merge code

@vuviettai
- Support compound type
  - Write data in order for the relationship constrain (cont.)
- Merge code with indexer manager

@thala321 
- Support @vuviettai for compound type.
  - [Indexer] Call API to track multiple tables in hasura (cont.)
- Set up a long run test (cont.)
- Merge code

@NhutVu23
- Add UI for auto get example list

@datzero9 
- Research use WASM plugin (maybe reuse the graph code) (cont.)

**Comment by anhhuy0501** [comment]
## 28 July
@anhhuy0501 task:
- Support compound type
  - Fix generate code rust (done)
- Write example for demo
- Review + Merge code

@vuviettai
- Support compound type
  - Write data in order for the relationship constrain (cont.)
  - Solve problem of concurrent write to and read from buffer
- Review + Merge code with indexer manager

@thala321 
- Support @vuviettai for compound type.
- Set up a long run test (cont.)
- Review + Merge code

@NhutVu23
- Test UI

@datzero9 
- Research use WASM plugin (maybe reuse the graph code) (cont.)

**Comment by anhhuy0501** [comment]
## 30 July
* We will do the demo today!
@anhhuy0501 task:
- Fix gen code
- Write query
- Review + Merge code

@vuviettai
- Support compound type
  - Write data in order for the relationship constrain (cont.)
- Review + Merge code with indexer manager

@thala321 
- Set up long time test
- Set up a long run test (cont.)
- Review + Merge code

@NhutVu23
- Test UI

@datzero9 
- Research use WASM plugin (maybe reuse the graph code) (cont.)

**Comment by vuviettai** [comment]
## 02 August
@vuvietai 
- Research support big data in hasura (around 10bil records per table)
@anhhuy0501 
- Optimize chain-reader
- Investigate stability on demo server

**Comment by vuviettai** [comment]
## 03 August
@anhhuy0501 

- Start support BSC for chain reader
@vuviettai 

- Start support BSC for plugin manager
@thala321 

- Reasearch framework for integration testing
@NhutVu23 

- Improve UI, follow new design

### Other notes

- Support multiple users at backend (no assignee)
- Currently aggregations on solana data are too slowly (raw data about 50mils records/day)

**Comment by anhhuy0501** [comment]
## 03 August
@anhhuy0501 :
- Start support BSC for chain reader (cont.)

@vuviettai :
- Start support BSC for plugin manager (cont.)

@thala321 :
- Reasearch framework for integration testing (cont.)
- Support restart indexer after turn-off

@NhutVu23 :
- Improve UI, follow new design

**Comment by anhhuy0501** [comment]
## 05 August
@anhhuy0501 :
- Start support BSC for chain reader (cont.)

@vuviettai :
- Start support BSC for plugin manager (cont.)

@thala321 :
- Fix CICD
- Add e2e test when CICD
- Support restart indexer after turn-off

@NhutVu23 :
- Improve UI, follow new design

**Comment by anhhuy0501** [comment]
## 16 August
@anhhuy0501 :
- Support BSC data for QuickSwap

@vuviettai :
- Support simple example for Wasm plugin 
- Support Wasm plugin function for QuickSwap

@thala321 :
- Run long test on Vu's PC
- Support simple example for Wasm plugin

@NhutVu23 :
- Support BSC chain on UI

@datzero9:
- Refactor code in chain-reader

**Comment by anhhuy0501** [comment]
## 16 August
@anhhuy0501 :
- Parse abi file for decode data 

@vuviettai :
- Store data in wasm plugin

@thala321 :
- upload abi file to IPFS

@NhutVu23 :
- Support BSC chain on UI

@datzero9:
- Refactor code

**Comment by anhhuy0501** [comment]
## 25 August
@anhhuy0501 :
- Contract call 

@vuviettai :
- Store data in wasm plugin

@thala321 :
- Logging improvement
@NhutVu23 :
- Support BSC chain on UI

@datzero9:
- Refactor code

**Comment by daywednes** [comment]
can we write the status of each task here too?

In the morning: task, 
The end of the day: Result.

**Comment by anhhuy0501** [comment]
## 30 August
@anhhuy0501 :
- Contract call:
  - Test ethereum call: fix bug that some time it stuck after the call
  - Ethereum call error problem: add retry

@vuviettai :
- Merge plugin/codegen in rust + wasm
- Understand QuickSwap sub-graph project in detail level:
  - From datasource to datasource template

@thala321 :
- Fix bug
- Understand QuickSwap sub-graph project in high level
  - There are multi contract address, how to check all address. Do we need check all address for indexing?

@NhutVu23:
- Support BSC chain on UI: wating for merging code

@datzero9:
- Refactor code chain-reader: on going

**Comment by anhhuy0501** [comment]
## 30 August
Target: get QuickSwap data into db, now only few data in db
@anhhuy0501 :
- Contract call:
  - Check with scan matic
- Check weather data in db is correct
- Debug

@vuviettai :
- Check store 
- Debug


@thala321 :
- Add retry to contract call
- Debug

@NhutVu23:
- Support BSC chain on UI: wating for merging code

@datzero9:
- Refactor code chain-reader: on going

**Comment by anhhuy0501** [comment]
## 31 August
Target: get QuickSwap data into db, now only few data in db
@anhhuy0501 :
- Debug:
  - Support fix bug
  - Add simple retry for chain-reader -> done

@vuviettai :
- Debug
  - Fix long run (out of resource) -> done
  - Add simple retry for ethreum call -> done


@thala321 :
- Debug
  - Check eth_call detail -> fix bug wrong block number -> done 
  - Add parse data_source for rust code

@NhutVu23:
- Support BSC chain on UI: wating for merging code

@datzero9:
- Refactor code chain-reader: later
- Debug: 
  - Add good retry

**Comment by anhhuy0501** [comment]
## 3 Sep.
Target: Full demo, both .wasm and .so
@anhhuy0501 :
- Fix manifest 
- Optimize decode time

@vuviettai :
- Fix bug
  - merge code .wasm an .so
  - DB relationship

@thala321 :
- Fix mainifest
- Improve compile time for wasm
- Check long time test

@NhutVu23:
- Support BSC chain on UI: wating for merging code

@datzero9:
- Refactor code chain-reader -> cont.
- Debug: 
  - Add full feature retry -> cont.

**Comment by anhhuy0501** [comment]
## 8 Sep.
Weekly target: run longer than 1 week data for Matic
@anhhuy0501 :
- add restart for chain-reader
- add lazy loading for chain-reader

@vuviettai :
- Merge code to main
- create Coin98 report data

@thala321 :
- Run other smart contract (such as pamcakeswap) and get data

@datzero9:
- Refactor code chain-reader -> cont.
- Debug: Fix solana cannot decode after merging with the ethreum code. -> cont.

**Comment by anhhuy0501** [comment]
## 8 Sep.
Weekly target: run longer than 1 week data for Matic
@anhhuy0501 :
- Support @vuviettai  getting data
- add lazy loading for chain-reader


@vuviettai :
- create Coin98 report data 
  - Get active address + new address -> cont.

@thala321 :
- Run other smart contract (such as pamcakeswap) and get data -> cont.
- Check whether data is correct?
- Run long test

@datzero9:
- Refactor code chain-reader -> cont.

**Comment by anhhuy0501** [comment]
## 9 Sep.
Weekly target: run longer than 1 week data for Matic
@anhhuy0501 :
- add lazy loading for chain-reader -> later
- Add Ethereum get data in batch for faster chain-reader


@vuviettai :
- create Coin98 report data 
  - Get active address + new address -> cont.
    - Add `load` function for Rust plugin 

@thala321 :
- Check whether data is correct? -> wait for data
- Set up long run test on Vu desktop
- Add checking long run test status
- Code-compiler support pancakeswap and uniswap folder structure

@datzero9:
- Refactor code chain-reader -> cont.

**Comment by anhhuy0501** [comment]
## 14 Sep.
Weekly target: run longer than 1 week + insert data is correct
@anhhuy0501 :
- Add Ethereum get data in batch for faster chain-reader
- Add load multi Ethereum chain type


@vuviettai :
- Fix bug: ethereum call from WASM file failed.
- Example for new Address/active address in ethereum

@thala321 :
- Help NFT team 

@datzero9:
- Fix bug: long run chain-reader stuck

**Comment by anhhuy0501** [comment]
## 16 Sep.
Weekly target: run longer than 1 week + insert data is correct
@anhhuy0501 :
- Fix bug: long run chain-reader stuck
- Run sub-graph pancake swap


@vuviettai :
- Fix bug: ethereum call from WASM file failed.
- Example for new Address/active address in ethereum

@baysao:
- Learn rust, block-chain
- Install develop environment
- Help NFT team 

@thala321 :
- Help NFT team 

@datzero9:
- Fix bug: long run chain-reader stuck 
- Add user filter to chain-reader (only take the block related to a specific contract)

**Comment by anhhuy0501** [comment]
## 20 Sep.
Weekly target: run longer than 1 week + insert data is correct + run pancake swap + index general chain-data
@anhhuy0501 :
- Fix bug: long run chain-reader stuck
- Add log to monitor  


@vuviettai :
- Example for new Address/active address in ethereum
- Index general chain-data

@baysao:
- Learn rust, block-chain
- Install develop environment

@thala321 :
- Contact + support P-OPS run Massbit test
- Update Code-compiler to run sub-graph pancake swap

@datzero9:
- Add user filter to chain-reader (only take the block related to a specific contract)
- Refactor chain-reader

**Comment by anhhuy0501** [comment]
## 22 Sep.
Weekly target: run longer than 1 week + insert data is correct + run pancake swap + index general chain-data
@anhhuy0501 :
- Long run check
- Cache data from chain to DB

@vuviettai :
- Example for new Address/active address in ethereum
- Index general chain-data

@baysao:
- Learn rust, block-chain
- Buy a server for testing + setup server

@thala321 :
- Contact + support P-OPS run Massbit test 
  - Write document for P-OPS start server
- Start both quickswap in the graph and Massbit for comparing data.

@datzero9:
- Add user filter to chain-reader (only take the block related to a specific contract)

**Comment by anhhuy0501** [comment]
## 22 Sep.
Weekly target: run longer than 1 week + insert data is correct + run pancake swap + index general chain-data
@anhhuy0501 :
- Long run check
- Cache data from chain to DB -> cont.

@vuviettai :
- Index general chain-data -> cont.

@baysao:
- Learn rust, block-chain
- Buy a server for testing + setup server 

@thala321 :
- Contact + support P-OPS run Massbit test -> cont.
  - Write document for P-OPS start server  
- Start both quickswap in the graph and Massbit for comparing data. -> cont.

@datzero9:
- Add user filter to chain-reader (only take the block related to a specific contract) -> cont.

**Comment by anhhuy0501** [comment]
## 24 Sep.
Weekly target: run longer than 1 week + insert data is correct + run pancake swap + index general chain-data
@anhhuy0501 :
- Long run check
- Cache data from chain to DB -> cont.

@vuviettai :
- Index general chain-data -> cont.
  - Save state of indexer for restart

@baysao:
- Learn rust, block-chain
- Replace macro code in plugin module.
- Buy another server for testing + setup server

@thala321 :
- Contact + support P-OPS run Massbit test -> cont.
  - Write document for P-OPS start server  
- Start both quickswap in the graph and Massbit for comparing data. -> cont.
  - Check why did the graph code stop

@datzero9:
- Add user filter to chain-reader (only take the block related to a specific contract) -> cont.

**Comment by anhhuy0501** [comment]
## 06 Oct.
Weekly target: solana hackathon first demo
@anhhuy0501 :
- Check solana filter -> 
  - old block: no filter
  - for new block: 
    - https://docs.solana.com/developing/clients/jsonrpc-api#programsubscribe or 
    - https://docs.solana.com/developing/clients/jsonrpc-api#logssubscribe
- Chain-reader 
  - Filter solana saber blocks (7/10)
  - Decode saber instructions (8/10)

@vuviettai :
- Index Solana general chain-data -> cont.
- Solana big data problem 

@baysao:
- MassbitRoute

@thala321 :
- Start Solana node: (7-8/10)

@datzero9:
- Merge GRPC chain-reader into index-manager
- Handle solana data at index-manager

**Comment by thala321** [comment]
No longer use daily note, we'll update in github project
