### ISSUE TITLE
Rust study

### ISSUE THREAD

**Issue by daywednes** [massbitprotocol/massbitprotocol#7]
https://github.com/mre/idiomatic-rust
https://github.com/ferrous-systems/elements-of-rust
https://www.possiblerust.com/
https://rust-lang.github.io/api-guidelines/
https://doc.rust-lang.org/stable/rust-by-example/

**Comment by thala321** [comment]
21-6-2021
https://www.possiblerust.com/
- Guide
  - How to Read Rust Functions, Part 1
  - Inbound & Outbound FFI
  - Enum or Trait Object 
- Patterns
  - Naming Your Lifetimes 
  - 3 Things to Try When You Can't Make a Trait Object
  - Non-Generic Inner Functions
  - Rust Lints You May Not Know
