### ISSUE TITLE
Indexer breakdown

### ISSUE THREAD

**Issue by datzero9** [massbitprotocol/massbitprotocol#9]
@anhhuy0501 

- [ ] Data streaming (Define protobuf, implement GRPC server, client)
- [ ] Block data decoder lib (Reference: https://github.com/subquery/subql/blob/main/packages/types/src/interfaces.ts)

@thala321 
- [ ] Index manager (load, store, run user defined index)

@datzero9 
- [ ] Plugin manager lib
- [ ] Index examples

**Comment by thala321** [comment]
Index manager (load, store, run user defined index)
- Progress (25-6-2021) https://github.com/massbitprotocol/massbitprotocol/commit/b04d90af32bcc812c4173dc441d94f0372856512
